name: Tag on Push to Main

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Get version from package.json
      id: package_version
      run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

    - name: Create and Push Tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag "v${{ steps.package_version.outputs.version }}"
        git push --tags
